// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCpNCgtBY3RvclN0YXR1cxIICgRJRExF",
            "EAASCgoGTU9WSU5HEAESDwoLSU5URVJBQ1RJTkcQAhIICgRERUFEEAMSDQoJ",
            "QVRUQUNLSU5HEAQqPQoJQWN0b3JSb2xlEgsKB0RFRkFVTFQQABIKCgZQTEFZ",
            "RVIQARIGCgJBSRACEg8KC0VOVklST05NRU5UEAMqUgoJRXJyb3JDb2RlEggK",
            "BE5PTkUQABIXChNJTlZBTElEX0NSRURFTlRJQUxTEAESDwoLU0VSVkVSX0ZV",
            "TEwQAhIRCg1VTktOT1dOX0VSUk9SEGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ActorStatus), typeof(global::Protocol.ActorRole), typeof(global::Protocol.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Actor의 상태
  /// </summary>
  public enum ActorStatus {
    /// <summary>
    /// 대기 중
    /// </summary>
    [pbr::OriginalName("IDLE")] Idle = 0,
    /// <summary>
    /// 이동 중
    /// </summary>
    [pbr::OriginalName("MOVING")] Moving = 1,
    /// <summary>
    /// 상호작용 중
    /// </summary>
    [pbr::OriginalName("INTERACTING")] Interacting = 2,
    /// <summary>
    /// 죽음
    /// </summary>
    [pbr::OriginalName("DEAD")] Dead = 3,
    /// <summary>
    /// 공격 중
    /// </summary>
    [pbr::OriginalName("ATTACKING")] Attacking = 4,
  }

  /// <summary>
  /// Actor의 상태를 확장하기 위한 상태 타입
  /// </summary>
  public enum ActorRole {
    /// <summary>
    /// 기본 역할
    /// </summary>
    [pbr::OriginalName("DEFAULT")] Default = 0,
    /// <summary>
    /// 사용자 조작 Actor
    /// </summary>
    [pbr::OriginalName("PLAYER")] Player = 1,
    /// <summary>
    /// AI로 동작
    /// </summary>
    [pbr::OriginalName("AI")] Ai = 2,
    /// <summary>
    /// 환경적 Actor (예: 나무, 바위)
    /// </summary>
    [pbr::OriginalName("ENVIRONMENT")] Environment = 3,
  }

  /// <summary>
  /// 에러 코드
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 성공
    /// </summary>
    [pbr::OriginalName("NONE")] None = 0,
    /// <summary>
    /// 잘못된 인증 정보
    /// </summary>
    [pbr::OriginalName("INVALID_CREDENTIALS")] InvalidCredentials = 1,
    /// <summary>
    /// 서버 가득 참
    /// </summary>
    [pbr::OriginalName("SERVER_FULL")] ServerFull = 2,
    /// <summary>
    /// 알 수 없는 에러
    /// </summary>
    [pbr::OriginalName("UNKNOWN_ERROR")] UnknownError = 99,
  }

  #endregion

}

#endregion Designer generated code
